name: Deploy to Server via FTP

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql, xml, ctype, json, openssl, tokenizer
        coverage: none

    - name: Install dependencies
      run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

    - name: Build assets
      run: |
        npm ci
        npm run build

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          /.git
          /.github
          /node_modules/**
          /tests
          /storage
          /storage
          .env
          .env.example

    - name: Deploy url
      run: curl -X GET https://host.tiagomatos.com/deploy
